--USE MASTER
--GO
--DROP DATABASE GARCIAS_DB

CREATE DATABASE GARCIAS_DB
GO
USE GARCIAS_DB
GO
CREATE TABLE CONTACTOS(
	IDCONTACTO INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	NOMBRE VARCHAR(80) NOT NULL,
	TELEFONO INT NULL,
	EMAIL VARCHAR(50) NULL,
	DIRECCION VARCHAR(50) NULL
	)
GO 
CREATE TABLE PROVEEDORES(
	IDPROV INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	CUIT VARCHAR(13) NOT NULL UNIQUE,
	IDCONTACTO INT NOT NULL FOREIGN KEY REFERENCES CONTACTOS(IDCONTACTO),
	FECHA_ALTA DATE NOT NULL,
	FECHA_BAJA DATE NULL,
	ULT_MOD DATE NULL,	
	[STATUS] INT NOT NULL
	)
GO
CREATE TABLE INSUMOS(
	IDINSUMO INT NOT NULL PRIMARY KEY IDENTITY (5000,1),
	DESCRIPCION VARCHAR(50) NOT NULL,
	VALOR_ULT_COMPRA MONEY NULL,
	FECHA_ULT_COMPRA DATE NULL,
	FECHA_ALTA DATE NOT NULL,
	FECHA_BAJA DATE NULL,
	ULT_MOD DATE NULL,	
	[STATUS] INT NOT NULL
	)
GO
CREATE TABLE COMPRAS(
	IDCOMPRA INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	CODPROV INT NOT NULL FOREIGN KEY REFERENCES PROVEEDORES(IDPROV),
	FECHA_COMPRA DATE NOT NULL,
	VALOR_COMPRA MONEY NOT NULL,
	NRODOCUMENTO VARCHAR(15) NULL,
	)
GO
CREATE TABLE DETALLE_COMPRAS(
	NROREMITO VARCHAR(15) NOT NULL,
	FECHAREMITO DATE NOT NULL,
	IDCOMPRA INT NOT NULL FOREIGN KEY REFERENCES COMPRAS(IDCOMPRA),
	INSUMO INT NOT NULL FOREIGN KEY REFERENCES INSUMOS(IDINSUMO),
	CANTIDAD INT NOT NULL,
	PRECIO_UNITARIO MONEY NOT NULL,
	PRIMARY KEY(NROREMITO,INSUMO)
	)
GO
CREATE TABLE CLIENTES(
	IDCLIENTE INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	CUIT VARCHAR(13) NOT NULL UNIQUE,
	IDCONTACTO INT NOT NULL FOREIGN KEY REFERENCES CONTACTOS(IDCONTACTO),
	FECHA_ALTA DATE NOT NULL,
	FECHA_BAJA DATE NULL,
	ULT_MOD DATE NULL,	
	[STATUS] INT NOT NULL
	)
GO
CREATE TABLE PRODUCTOS(
	IDPROD INT NOT NULL IDENTITY (1000,1) PRIMARY KEY,
	DESCRIPCION VARCHAR(50) NOT NULL,
	VALOR MONEY NOT NULL,
	FECHA_ULT_VTA DATE NULL,
	FECHA_ALTA DATE NOT NULL,
	FECHA_BAJA DATE NULL,
	ULT_MOD DATE NULL,	
	[STATUS] INT NOT NULL
	)
GO 
CREATE TABLE VENTAS(
	IDVENTA INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	FECHA_VTA DATE NOT NULL,
	IDCLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(IDCLIENTE),
	)
GO
CREATE TABLE DETALLE_VENTAS(
	IDVENTA INT NOT NULL FOREIGN KEY REFERENCES VENTAS(IDVENTA),
	PRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(IDPROD),
	CANTIDAD INT NOT NULL,
	VALOR MONEY NOT NULL
	PRIMARY KEY(PRODUCTO,IDVENTA)
)
GO
CREATE TABLE PEDIDOS(
	IDPEDIDO INT NOT NULL IDENTITY (1,1) UNIQUE,
	IDVENTA INT NOT NULL FOREIGN KEY REFERENCES VENTAS(IDVENTA),
	FECHA_PEDIDO DATE NOT NULL,	
	FECHA_ENTREGA_ACORDADA DATE NOT NULL,
	FECHA_ENTREGA_REAL DATE NULL,
	[STATUS] INT NOT NULL,
	PRIMARY KEY (IDVENTA, IDPEDIDO)
	)
GO
CREATE TABLE DETALLE_PEDIDO(
	IDPEDIDO INT NOT NULL FOREIGN KEY REFERENCES PEDIDOS(IDPEDIDO),
	IDINSUMO INT NOT NULL FOREIGN KEY REFERENCES INSUMOS(IDINSUMO),
	CANTIDAD INT NOT NULL,
	PRIMARY KEY(IDPEDIDO,IDINSUMO)
	)
GO
CREATE TABLE STOCK(
	IDMATERIAL INT NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(50) NOT NULL,
	CANTIDAD INT NOT NULL
)
GO

CREATE TRIGGER TR_BAJA_INSUMOS ON DETALLE_PEDIDO
INSTEAD OF INSERT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
			DECLARE @CANTIDAD INT
			DECLARE @IDPEDIDO INT
			DECLARE @IDINSUMO INT
			
			SELECT @CANTIDAD = CANTIDAD, @IDPEDIDO = IDPEDIDO ,@IDINSUMO = IDINSUMO FROM INSERTED
			
			IF(((SELECT CANTIDAD FROM STOCK WHERE IDMATERIAL = @IDINSUMO)-@CANTIDAD)>=0)
			BEGIN
				INSERT INTO DETALLE_PEDIDO (IDPEDIDO,IDINSUMO,CANTIDAD) VALUES (@IDPEDIDO,@IDINSUMO,@CANTIDAD)
				
				UPDATE STOCK SET CANTIDAD = CANTIDAD - @CANTIDAD WHERE IDMATERIAL = @IDINSUMO
			END
			ELSE
			BEGIN
				RAISERROR('NO HAY STOCK SUFICIENTE',16,1)
			END
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0 BEGIN
			ROLLBACK TRANSACTION
		END
		PRINT ERROR_MESSAGE()
	END CATCH
END

GO
CREATE TRIGGER TR_INGRESO_INSUMOS ON DETALLE_COMPRAS
AFTER INSERT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
			DECLARE @CANTIDAD INT
			DECLARE @IDINSUMO INT
			DECLARE @VALOR MONEY
						
			SELECT @CANTIDAD = CANTIDAD, @IDINSUMO = INSUMO,@VALOR = PRECIO_UNITARIO FROM INSERTED
			
			UPDATE STOCK SET CANTIDAD = CANTIDAD + @CANTIDAD WHERE IDMATERIAL = @IDINSUMO
			UPDATE INSUMOS SET VALOR_ULT_COMPRA = @VALOR, FECHA_ULT_COMPRA = GETDATE(), ULT_MOD = GETDATE() WHERE IDINSUMO = @IDINSUMO
			
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0 BEGIN
			ROLLBACK TRANSACTION
		END
		RAISERROR('ERROR AL INGRESAR EL INSUMO', 16, 1)
	END CATCH
END

GO
CREATE TRIGGER TR_CREACION_INSUMO ON INSUMOS
AFTER INSERT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
			DECLARE @IDINSUMO INT
			DECLARE @DESC VARCHAR(50)
						
			SELECT @IDINSUMO = IDINSUMO, @DESC = DESCRIPCION FROM INSERTED
			IF (@IDINSUMO  NOT IN (SELECT IDMATERIAL FROM STOCK))
				BEGIN
				INSERT INTO STOCK (IDMATERIAL,DESCRIPCION,CANTIDAD) VALUES (@IDINSUMO,@DESC,0)	
				END
				
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0 BEGIN
			ROLLBACK TRANSACTION
		END
		RAISERROR('ERROR AL CREAR INSUMO', 16, 1)
	END CATCH
END

GO
CREATE TRIGGER TR_CREACION_PROD ON PRODUCTOS
AFTER INSERT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
			DECLARE @IDPROD INT
			DECLARE @DESC VARCHAR(50)
						
			SELECT @IDPROD = IDPROD, @DESC = DESCRIPCION FROM INSERTED
			IF (@IDPROD NOT IN (SELECT IDMATERIAL FROM STOCK))
				BEGIN
				INSERT INTO STOCK (IDMATERIAL,DESCRIPCION,CANTIDAD) VALUES (@IDPROD,@DESC,0)	
				END
		
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0 BEGIN
			ROLLBACK TRANSACTION
		END
		RAISERROR('ERROR AL CREAR PRODUCTO', 16, 1)
	END CATCH
END



GO
    INSERT INTO CONTACTOS (NOMBRE,TELEFONO,EMAIL,DIRECCION) VALUES ('ADRIAN CACCAVIELLO', 1538845385, 'ADRI_KK@GMAIL.COM','LIMA 1501, PACHECO')
    INSERT INTO CONTACTOS (NOMBRE,TELEFONO,EMAIL,DIRECCION) VALUES ('LUCAS ADELMANN', 1541381234, 'ANDY_LUKETI@GMAIL.COM','BALCARCE 83, PACHECO')
    INSERT INTO CONTACTOS (NOMBRE,TELEFONO,EMAIL,DIRECCION) VALUES ('LAUTARO LUPANI', 47362411, 'LAUTARO.LUPANI@TREKEN.COM.AR','PAUL GROUSAC 2405, LOPEZ CAMELO')
    INSERT INTO CONTACTOS (NOMBRE,TELEFONO,EMAIL,DIRECCION) VALUES ('FRANCO BARBIERI', 47407847, 'VIKTIMA_22@GMAIL.COM','ALBERDI 203, PACHECO')
GO
    INSERT INTO PROVEEDORES (NOMBRE,CUIT,IDCONTACTO,FECHA_ALTA,FECHA_BAJA,ULT_MOD,[STATUS]) VALUES ('FERRETERIA GONZALEZ','30-25338134-2',1,'6/10/2018',NULL,'6/10/2018',1)
    INSERT INTO PROVEEDORES (NOMBRE,CUIT,IDCONTACTO,FECHA_ALTA,FECHA_BAJA,ULT_MOD,[STATUS]) VALUES ('TREKEN S.A','30-50918302-7',3,'6/10/2018',NULL,'6/10/2018',1)
GO
    INSERT INTO INSUMOS (DESCRIPCION,VALOR_ULT_COMPRA,FECHA_ULT_COMPRA,FECHA_ALTA,FECHA_BAJA,ULT_MOD,[STATUS]) VALUES ('PERFIL 3/4',450,'1/7/2018','6/10/2018',NULL,'6/10/2018',1)
    INSERT INTO INSUMOS (DESCRIPCION,VALOR_ULT_COMPRA,FECHA_ULT_COMPRA,FECHA_ALTA,FECHA_BAJA,ULT_MOD,[STATUS]) VALUES ('SELLADOR',250,'8/9/2018','6/10/2018',NULL,'6/10/2018',1)
GO
    INSERT INTO COMPRAS (CODPROV,FECHA_COMPRA,VALOR_COMPRA,NRODOCUMENTO) VALUES (1,'10/9/2018',900,'0001A00001234')
    INSERT INTO COMPRAS (CODPROV,FECHA_COMPRA,VALOR_COMPRA,NRODOCUMENTO) VALUES (2,'10/9/2018',500,'0001A00000394')
    INSERT INTO COMPRAS (CODPROV,FECHA_COMPRA,VALOR_COMPRA,NRODOCUMENTO) VALUES (1,'20/9/2018',1800,'0001A00001265')
    INSERT INTO COMPRAS (CODPROV,FECHA_COMPRA,VALOR_COMPRA,NRODOCUMENTO) VALUES (2,'20/9/2018',750,'0001A00000416')
GO
    INSERT INTO DETALLE_COMPRAS (NROREMITO,FECHAREMITO,IDCOMPRA,INSUMO,CANTIDAD,PRECIO_UNITARIO) VALUES ('0001R00007789','14/9/2018',1,5000,10,90)
    INSERT INTO DETALLE_COMPRAS (NROREMITO,FECHAREMITO,IDCOMPRA,INSUMO,CANTIDAD,PRECIO_UNITARIO) VALUES ('0001R00001245','10/9/2018',2,5001,20,25)
    INSERT INTO DETALLE_COMPRAS (NROREMITO,FECHAREMITO,IDCOMPRA,INSUMO,CANTIDAD,PRECIO_UNITARIO) VALUES ('0001R00007837','25/9/2018',3,5000,20,90)
    INSERT INTO DETALLE_COMPRAS (NROREMITO,FECHAREMITO,IDCOMPRA,INSUMO,CANTIDAD,PRECIO_UNITARIO) VALUES ('0001R00001378','21/9/2018',1,5001,15,25) 
GO
    INSERT INTO CLIENTES (NOMBRE,CUIT,IDCONTACTO,FECHA_ALTA,FECHA_BAJA,ULT_MOD,[STATUS]) VALUES ('PATRICIA GONZALEZ','27-25338134-4',4,'6/10/2018',NULL,'6/10/2018',1)
    INSERT INTO CLIENTES (NOMBRE,CUIT,IDCONTACTO,FECHA_ALTA,FECHA_BAJA,ULT_MOD,[STATUS]) VALUES ('FRANCO BARBIERI','20-32392192-7',2,'6/10/2018',NULL,'6/10/2018',1)
GO
	INSERT INTO PRODUCTOS (DESCRIPCION,VALOR,FECHA_ULT_VTA,FECHA_ALTA,FECHA_BAJA,ULT_MOD,[STATUS]) VALUES ('VENTANA A MEDIDA 2x4',3500,'10/10/2018','01/01/2018',NULL,'10/10/2018',1)
    INSERT INTO PRODUCTOS (DESCRIPCION,VALOR,FECHA_ULT_VTA,FECHA_ALTA,FECHA_BAJA,ULT_MOD,[STATUS]) VALUES ('VENTANA ESTANDAR 1,8x2',1500,'18/9/2018','6/10/2017',NULL,'6/10/2018',1)
GO
    INSERT INTO VENTAS (FECHA_VTA,IDCLIENTE) VALUES ('19/11/2018',1)
    INSERT INTO VENTAS (FECHA_VTA,IDCLIENTE) VALUES ('19/11/2018',2)
GO
    INSERT INTO DETALLE_VENTAS (IDVENTA,PRODUCTO,CANTIDAD,VALOR) VALUES (1,1000,5,18000)
    INSERT INTO DETALLE_VENTAS (IDVENTA,PRODUCTO,CANTIDAD,VALOR) VALUES (2,1001,8,15000)
GO
    INSERT INTO PEDIDOS (IDVENTA,FECHA_PEDIDO,FECHA_ENTREGA_ACORDADA,FECHA_ENTREGA_REAL,[STATUS]) VALUES (1,'19/11/2018','18/01/2019',NULL,1)
    INSERT INTO PEDIDOS (IDVENTA,FECHA_PEDIDO,FECHA_ENTREGA_ACORDADA,FECHA_ENTREGA_REAL,[STATUS]) VALUES (2,'19/11/2018','4/02/2019',NULL,1)
GO
    INSERT INTO DETALLE_PEDIDO(IDPEDIDO,IDINSUMO,CANTIDAD) VALUES (1,5000,10)
    INSERT INTO DETALLE_PEDIDO(IDPEDIDO,IDINSUMO,CANTIDAD) VALUES (1,5001,5)
    INSERT INTO DETALLE_PEDIDO(IDPEDIDO,IDINSUMO,CANTIDAD) VALUES (2,5000,20)
    INSERT INTO DETALLE_PEDIDO(IDPEDIDO,IDINSUMO,CANTIDAD) VALUES (2,5001,10)
